apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
- deployment.yaml
- service.yaml
images:
- name: transfers
  newName: europe-west2-docker.pkg.dev/cyberark-gitops-3a49df/cyberark-images-3a49df/transfers
  newTag: latest
