apiVersion: v1
kind: Service
metadata:
  name: transfers
  namespace: apps
  labels:
    app: transfers
spec:
  selector:
    app: transfers
  ports:
  - name: http
    port: 8081
    targetPort: http
