apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kube-prometheus-stack-app.yaml
- tempo-app.yaml
- otel-collector-app.yaml
commonAnnotations:
  argocd.argoproj.io/sync-wave: "-8"
