apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: oci://registry-1.docker.io/bitnamicharts
    chart: postgresql
    targetRevision: 18.2.3
    helm:
      releaseName: postgres
      values: |
        primary:
          persistence:
            size: 8Gi
        audit:
          logHostname: false
  destination:
    namespace: db
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
